version: '3'
services:
  pgsql:
    user: "${CONTAINER_USER}:${CONTAINER_USER}"
    image: postgres:${VERSION}
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - databases

networks:
  databases:
    external:
      name: databases
